name: Build Python with OpenSSL on MacOS 

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        run: |
          # Download and extract Python
          wget https://www.python.org/ftp/python/3.13.0/Python-3.13.0.tgz
          tar -xvf Python-3.13.0.tgz

      - name: Set up OpenSSL
        run: |
          # Download and extract OpenSSL
          wget https://www.openssl.org/source/openssl-3.3.2.tar.gz
          tar -xvf openssl-3.3.2.tar.gz

      - name: Install OpenSSL
        run: |
          cd openssl-3.3.2
          ./Configure --prefix=/usr/local/openssl-3.3.2
          make -j $(sysctl -n hw.ncpu)
          sudo make install

      - name: Create OpenSSL macOS Installer Package
        run: |
          pkgbuild --root /usr/local/openssl-3.3.2 --identifier org.enmoe.openssl --version 3.3.2 --install-location /usr/local/openssl-3.3.2 openssl-3.3.2.pkg

      - name: Build and Install Python
        run: |
          cd Python-3.13.0
          ./configure --prefix=/usr/local/Python-3.13.0 --enable-optimizations --with-openssl=/usr/local/openssl-3.3.2
          make -j $(sysctl -n hw.ncpu)
          sudo make install

      - name: Create Python macOS Installer Package
        run: |
          pkgbuild --root /usr/local/Python-3.13.0 --identifier org.enmoe.python --version 3.13.0 --install-location /usr/local/Python-3.13.0 python-3.13.0.pkg

      - name: Clean Up
        run: |
          sudo rm -rf openssl-3.3.2
          sudo rm -rf Python-3.13.0

      - name: Verify Python and OpenSSL Installation
        run: |
          /usr/local/Python-3.13.0/bin/python3 --version
          /usr/local/Python-3.13.0/bin/python3 -c "import ssl; print(ssl.OPENSSL_VERSION)"

      - name: Upload OpenSSL macOS Installer Package
        uses: actions/upload-artifact@v4
        with:
          name: openssl-3.3.2.pkg
          path: openssl-3.3.2.pkg

      - name: Upload Python macOS Installer Package
        uses: actions/upload-artifact@v4
        with:
          name: python-3.13.0.pkg
          path: python-3.13.0.pkg
